version: "3.9"

services:
  btc-bot:
    build: .
    container_name: btc-bot-container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
      - ./ip_whitelist.txt:/usr/src/app/ip_whitelist.txt
